volumes:
  userservice_local_postgres_data: {}
  userservice_local_postgres_data_backups: {}

services:
  postgres-service:
    image: postgres:latest
    container_name: user_service_postgres_db
    env_file:
      - ./.envs/.local/.postgres
    volumes:
      - userservice_local_postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5431" # I have local instance postgres running.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_dev_local -d user_service_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-service:
    image: redis:latest
    container_name: user_service_redis_db
    ports:
      - "6379:6379"

  user-service:
    depends_on:
      - postgres-service
      - redis-service
    build:
      context: .
      dockerfile: ./compose/local/user-service/Dockerfile
    image: tsotetsi/ticketflow-user-service:v1.0.0.alpha
    container_name: ticketflow-local-userservice
    env_file:
      - ./.envs/.local/.userservice
    ports:
      - '8000:8000'
    command: /start