services:
  user-service:
    build:
      context: .
      dockerfile: ./compose/local/user-service/Dockerfile
    image: tsotetsi/ticketflow-user-service:v1.0.0.alpha
    container_name: ticketflow-local-userservice
    env_file:
      - ./.envs/.local/.userservice
    ports:
      - '8000:8000'
    command: /start
