apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14 # Use a stable PostgreSQL version
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "user_dev_local"
            - name: POSTGRES_PASSWORD
              value: "@changeMe1234"
            - name: POSTGRES_DB
              value: "user_service_db"
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}  # Replace with PersistentVolumeClaim for production